import Head from 'next/head'
import Main from '@/components/Main'
import GameModes from '@/components/GameModes'
import Categories from '@/components/Categories'

export default function Home() {

  return (
    <>
      <Head>
        <title>Quizi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <GameModes />
      <Categories />
    </>
  )
}
