import Image from 'next/image'
import soundOn from "../assets/sound-on.svg"
import soundOff from "../assets/sound-off.svg"
import { useState } from 'react';
import { MdInfo } from 'react-icons/md'
import { GoAlert } from 'react-icons/go';

export default function Footer({ alert = false }) {
	const [sound, setSound] = useState(true);
	const [showInfo, setShowInfo] = useState(false);

	return (
		<footer className='absolute right-4 bottom-3'>
			<nav>
				<ul className='flex gap-4'>

					<li className='relative'>
						<button title='Show info' className={`align-middle relative z-20 hover:scale-105 p-1 bg-white rounded-md ${showInfo ? "scale-110" : ""}`} onClick={() => setShowInfo(!showInfo)}>
							{
								alert
									? <GoAlert className='text-2xl mx-auto' color='#0f172a' />
									: <MdInfo className='text-[25px]' style={{ color: "#1c233a" }} />
							}
						</button>
						<p className={`absolute text-sm md:text-base top-0 whitespace-nowrap bg-white text-slate-900 rounded-md py-1 px-4 text-left transition-all ${showInfo ? 'opacity-100 right-7 ' : 'opacity-0 right-0 pointer-events-none'}`}>
							{
								alert
									? "Because the questions are generated by AI, the answers may not be correct."
									: <span><a href="https://github.com/cosmoart/quiz-game" target="_blank" rel="noopener noreferrer" className='underline'>MIT licence</a> - Made with ❤️ by <a href="https://github.com/cosmoart" target="_blank" rel="noreferrer" className='underline'>Cosmo</a></span>
							}
						</p>
					</li>

					<li>
						<button title={sound ? "Mute" : "Play music"} className='align-middle hover:scale-105 p-1 bg-white rounded-md' onClick={() => setSound(!sound)}>
							{
								sound ?
									<Image src={soundOn} className="" alt="" width={25} height={25} onClick={() => setSound(false)} />
									:
									<Image src={soundOff} className="" alt="" width={25} height={25} onClick={() => setSound(true)} />
							}
						</button>
					</li>

				</ul>
			</nav>
		</footer>
	)
}